/**
 * Copy-Paste Typography Snippet Generator
 *
 * `fetchtype snippet inter+crimson-pro` → complete, production-ready CSS
 * with font imports, type scale, fallback overrides, and dark mode in
 * one copy-paste block. 30 seconds to dramatically better typography.
 */

import type { FontEntry } from '@fetchtype/types';
import { resolveFont } from '@fetchtype/fonts';
import { generateFallbackCSS } from './fallback.js';
import { SCALE_RATIOS, computeHeadingSizes } from './scale.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SnippetOptions = {
  /** Primary (body) font ID or family name */
  primary: string;
  /** Heading font ID or family name (optional — uses primary if omitted) */
  heading?: string;
  /** Monospace font for code (optional) */
  mono?: string;
  /** Type scale name (default: 'major-third') */
  scale?: string;
  /** Base font size in px (default: 16) */
  baseSizePx?: number;
  /** Include dark mode (default: true) */
  darkMode?: boolean;
  /** Include fallback overrides (default: true) */
  fallbacks?: boolean;
  /** Brand color hex (optional — generates accent colors) */
  brandColor?: string;
};

export type SnippetResult = {
  css: string;
  fonts: {
    primary: FontEntry | undefined;
    heading: FontEntry | undefined;
    mono: FontEntry | undefined;
  };
  googleFontsLink: string;
  summary: string[];
};

// ---------------------------------------------------------------------------
// Color helpers
// ---------------------------------------------------------------------------

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const h = hex.replace('#', '');
  return {
    r: parseInt(h.substring(0, 2), 16),
    g: parseInt(h.substring(2, 4), 16),
    b: parseInt(h.substring(4, 6), 16),
  };
}

function rgbToHex(r: number, g: number, b: number): string {
  return `#${[r, g, b].map(c => Math.max(0, Math.min(255, Math.round(c))).toString(16).padStart(2, '0')).join('')}`;
}

function lighten(hex: string, amount: number): string {
  const { r, g, b } = hexToRgb(hex);
  return rgbToHex(
    r + (255 - r) * amount,
    g + (255 - g) * amount,
    b + (255 - b) * amount,
  );
}

function darken(hex: string, amount: number): string {
  const { r, g, b } = hexToRgb(hex);
  return rgbToHex(r * (1 - amount), g * (1 - amount), b * (1 - amount));
}

function luminance(hex: string): number {
  const { r, g, b } = hexToRgb(hex);
  const toLinear = (c: number) => {
    const srgb = c / 255;
    return srgb <= 0.03928 ? srgb / 12.92 : ((srgb + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
}

// ---------------------------------------------------------------------------
// Main function
// ---------------------------------------------------------------------------

export function generateSnippet(options: SnippetOptions): SnippetResult {
  const {
    scale = 'major-third',
    baseSizePx = 16,
    darkMode = true,
    fallbacks = true,
    brandColor,
  } = options;

  const primaryFont = resolveFont(options.primary);
  const headingFont = options.heading ? resolveFont(options.heading) : undefined;
  const monoFont = options.mono ? resolveFont(options.mono) : undefined;

  const primaryFamily = primaryFont?.family ?? options.primary;
  const headingFamily = headingFont?.family ?? options.heading ?? primaryFamily;
  const monoFamily = monoFont?.family ?? options.mono;

  // Build font stacks
  const primaryCategory = primaryFont?.category ?? 'sans-serif';
  const headingCategory = headingFont?.category ?? primaryCategory;

  const primaryStack = buildFontStack(primaryFamily, primaryCategory);
  const headingStack = buildFontStack(headingFamily, headingCategory);
  const monoStack = monoFamily ? `"${monoFamily}", ui-monospace, monospace` : 'ui-monospace, monospace';

  // Compute heading sizes
  const ratio = SCALE_RATIOS[scale as keyof typeof SCALE_RATIOS] ?? 1.25;
  const headingSizes = computeHeadingSizes(baseSizePx, ratio);

  // Colors
  const accent = brandColor ?? '#2563eb';
  const accentLight = lighten(accent, 0.85);
  const accentHover = darken(accent, 0.1);

  // Generate Google Fonts link
  const googleFontsLink = buildGoogleFontsLink(primaryFont, headingFont, monoFont);

  const lines: string[] = [];
  const summary: string[] = [];

  // -- Header comment --
  lines.push('/*');
  lines.push(` * Typography: ${headingFamily !== primaryFamily ? `${headingFamily} + ${primaryFamily}` : primaryFamily}${monoFamily ? ` + ${monoFamily}` : ''}`);
  lines.push(` * Scale: ${scale} (${ratio})`);
  lines.push(` * Generated by fetchtype — https://fetchtype.com`);
  lines.push(' */');
  lines.push('');

  // -- Google Fonts import --
  if (googleFontsLink) {
    lines.push(`@import url('${googleFontsLink}');`);
    lines.push('');
  }

  // -- Fallback overrides --
  if (fallbacks) {
    if (primaryFont) {
      const fallbackCss = generateFallbackCSS(primaryFont, { compact: true });
      if (fallbackCss.trim()) {
        lines.push('/* Fallback metric overrides — eliminates layout shift */');
        lines.push(fallbackCss);
        lines.push('');
      }
    }
  }

  // -- CSS Variables --
  lines.push(':root {');
  lines.push('  /* Typography */');
  lines.push(`  --font-body: ${primaryStack};`);
  if (headingFamily !== primaryFamily) {
    lines.push(`  --font-heading: ${headingStack};`);
  }
  if (monoFamily) {
    lines.push(`  --font-mono: ${monoStack};`);
  }
  lines.push('');
  lines.push('  /* Type scale */');
  lines.push(`  --text-xs: ${round(baseSizePx * 0.75)}px;`);
  lines.push(`  --text-sm: ${round(baseSizePx * 0.875)}px;`);
  lines.push(`  --text-base: ${baseSizePx}px;`);
  lines.push(`  --text-lg: ${round(baseSizePx * 1.125)}px;`);
  lines.push(`  --text-xl: ${round(baseSizePx * 1.25)}px;`);
  lines.push(`  --text-h6: ${round(headingSizes.h6)}px;`);
  lines.push(`  --text-h5: ${round(headingSizes.h5)}px;`);
  lines.push(`  --text-h4: ${round(headingSizes.h4)}px;`);
  lines.push(`  --text-h3: ${round(headingSizes.h3)}px;`);
  lines.push(`  --text-h2: ${round(headingSizes.h2)}px;`);
  lines.push(`  --text-h1: ${round(headingSizes.h1)}px;`);
  lines.push('');
  lines.push('  /* Colors */');
  lines.push('  --color-text: #111827;');
  lines.push('  --color-text-muted: #6b7280;');
  lines.push(`  --color-accent: ${accent};`);
  lines.push(`  --color-accent-hover: ${accentHover};`);
  lines.push(`  --color-accent-light: ${accentLight};`);
  lines.push('  --color-bg: #ffffff;');
  lines.push('  --color-bg-muted: #f3f4f6;');
  lines.push('  --color-border: #e5e7eb;');
  lines.push('}');
  lines.push('');

  // -- Dark mode --
  if (darkMode) {
    const darkAccent = luminance(accent) < 0.3 ? lighten(accent, 0.3) : accent;
    lines.push('@media (prefers-color-scheme: dark) {');
    lines.push('  :root {');
    lines.push('    --color-text: #f9fafb;');
    lines.push('    --color-text-muted: #9ca3af;');
    lines.push(`    --color-accent: ${darkAccent};`);
    lines.push(`    --color-accent-hover: ${lighten(darkAccent, 0.15)};`);
    lines.push(`    --color-accent-light: ${darken(accent, 0.6)};`);
    lines.push('    --color-bg: #111827;');
    lines.push('    --color-bg-muted: #1f2937;');
    lines.push('    --color-border: #374151;');
    lines.push('  }');
    lines.push('}');
    lines.push('');
  }

  // -- Base styles --
  lines.push('/* Base styles */');
  lines.push('body {');
  lines.push('  font-family: var(--font-body);');
  lines.push(`  font-size: var(--text-base);`);
  lines.push('  line-height: 1.6;');
  lines.push('  color: var(--color-text);');
  lines.push('  background: var(--color-bg);');
  lines.push('  -webkit-font-smoothing: antialiased;');
  lines.push('  -moz-osx-font-smoothing: grayscale;');
  lines.push('}');
  lines.push('');

  // -- Headings --
  const headingLevels = [
    { tag: 'h1', size: 'h1', lh: 1.05, ls: '-0.025em', weight: 700 },
    { tag: 'h2', size: 'h2', lh: 1.1, ls: '-0.02em', weight: 700 },
    { tag: 'h3', size: 'h3', lh: 1.15, ls: '-0.015em', weight: 600 },
    { tag: 'h4', size: 'h4', lh: 1.2, ls: '-0.01em', weight: 600 },
    { tag: 'h5', size: 'h5', lh: 1.3, ls: '0', weight: 600 },
    { tag: 'h6', size: 'h6', lh: 1.4, ls: '0', weight: 600 },
  ];

  lines.push(`h1, h2, h3, h4, h5, h6 {`);
  if (headingFamily !== primaryFamily) {
    lines.push('  font-family: var(--font-heading);');
  }
  lines.push('  color: var(--color-text);');
  lines.push('  text-wrap: balance;');
  lines.push('}');
  lines.push('');

  for (const h of headingLevels) {
    lines.push(`${h.tag} { font-size: var(--text-${h.size}); line-height: ${h.lh}; font-weight: ${h.weight}; letter-spacing: ${h.ls}; }`);
  }
  lines.push('');

  // -- Prose --
  lines.push('/* Prose */');
  lines.push('p { max-width: 68ch; }');
  lines.push('a { color: var(--color-accent); text-decoration-thickness: 1px; text-underline-offset: 2px; }');
  lines.push('a:hover { color: var(--color-accent-hover); }');
  if (monoFamily) {
    lines.push(`code, pre { font-family: var(--font-mono); font-size: 0.9375em; }`);
  }
  lines.push('small, .text-sm { font-size: var(--text-sm); }');
  lines.push('.text-muted { color: var(--color-text-muted); }');

  summary.push(
    `Fonts: ${[primaryFamily, headingFamily !== primaryFamily ? headingFamily : null, monoFamily].filter(Boolean).join(' + ')}`,
    `Scale: ${scale} (${ratio}) from ${baseSizePx}px base`,
    `Headings: ${round(headingSizes.h1)}px → ${round(headingSizes.h6)}px`,
    `${darkMode ? 'Dark mode included' : 'Light mode only'}`,
    `${fallbacks && primaryFont ? 'CLS-safe fallback overrides included' : 'No fallback overrides'}`,
  );

  return {
    css: lines.join('\n'),
    fonts: { primary: primaryFont, heading: headingFont, mono: monoFont },
    googleFontsLink,
    summary,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildFontStack(family: string, category: string): string {
  const generic = category === 'serif' ? 'serif'
    : category === 'monospace' ? 'monospace'
    : 'sans-serif';

  const systemFallbacks = generic === 'serif'
    ? '"Georgia", "Times New Roman", serif'
    : generic === 'monospace'
    ? 'ui-monospace, monospace'
    : 'system-ui, -apple-system, sans-serif';

  return `"${family}", ${systemFallbacks}`;
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

function buildGoogleFontsLink(
  primary: FontEntry | undefined,
  heading: FontEntry | undefined,
  mono: FontEntry | undefined,
): string {
  const fonts: string[] = [];

  for (const font of [primary, heading, mono]) {
    if (!font || font.source !== 'google') continue;
    const family = font.family.replace(/ /g, '+');

    if (font.variable) {
      const hasItalic = font.styles.includes('italic');
      if (hasItalic) {
        fonts.push(`family=${family}:ital,wght@0,100..900;1,100..900`);
      } else {
        fonts.push(`family=${family}:wght@100..900`);
      }
    } else {
      const weights = font.weights.join(';');
      fonts.push(`family=${family}:wght@${weights}`);
    }
  }

  if (fonts.length === 0) return '';
  // Deduplicate
  const unique = [...new Set(fonts)];
  return `https://fonts.googleapis.com/css2?${unique.join('&')}&display=swap`;
}
