/**
 * System font entries for the fetchtype registry.
 *
 * These are platform system fonts that ship pre-installed on rendering targets.
 * They have full FontEntry records so agents can recommend them for zero-payload
 * deployments and the enrichment pipeline can use their metrics for fallback computation.
 */

import type { FontEntry } from '@fetchtype/types';

const today = new Date().toISOString().split('T')[0];

function systemEntry(
  overrides: Partial<FontEntry> & Pick<FontEntry, 'id' | 'family' | 'category' | 'install'>,
): FontEntry {
  return {
    version: 'system',
    source: 'system',
    lastUpdated: today,
    tags: [],
    contexts: [],
    variable: false,
    axes: [],
    weights: [400, 700],
    styles: ['normal'],
    subsets: ['latin'],
    formats: [],
    hasItalic: false,
    hasOpticalSizing: false,
    performance: {
      woff2Size: {},
      variableFileSize: null,
      estimatedPayload: 0,
      loadingImpact: 'minimal',
    },
    metrics: {
      unitsPerEm: 1000,
      ascent: 800,
      descent: -200,
      lineGap: 0,
      xHeight: null,
      capHeight: null,
      useTypoMetrics: true,
      hheaAscent: null,
      hheaDescent: null,
      winAscent: null,
      winDescent: null,
    },
    fallback: {
      targets: [],
      requiresPlatformSplit: false,
      generatedCSS: '',
    },
    pairing: { recommended: [] },
    license: {
      type: 'Proprietary',
      url: '',
      commercial: true,
      selfHostable: false,
      attribution: null,
    },
    ...overrides,
  };
}

const sys = (
  platforms: ('apple' | 'windows' | 'android' | 'linux' | 'universal')[],
  localNames: string[],
  cssKeywords: string[] = [],
  note: string | null = null,
) => ({
  fontsource: null,
  googleCdn: null,
  npmPackage: null,
  system: { platforms, localNames, cssKeywords, note },
});

export const SYSTEM_FONT_ENTRIES: FontEntry[] = [
  // ── Apple ──
  systemEntry({
    id: 'sf-pro',
    family: 'SF Pro',
    category: 'sans-serif',
    contexts: ['interface', 'reading', 'display'],
    variable: true,
    axes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400, step: 1, cssProperty: 'font-weight' }],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    hasOpticalSizing: true,
    tags: ['neo-grotesque', 'system'],
    metrics: {
      unitsPerEm: 2048, ascent: 1950, descent: -420, lineGap: 0,
      xHeight: 1078, capHeight: 1443, useTypoMetrics: true,
      hheaAscent: 1950, hheaDescent: -420, winAscent: 2160, winDescent: 540,
    },
    license: { type: 'Apple EULA', url: 'https://developer.apple.com/fonts/', commercial: true, selfHostable: false, attribution: 'Apple Inc.' },
    install: sys(['apple'], ['.AppleSystemUIFont', 'SF Pro'], ['system-ui', '-apple-system', 'BlinkMacSystemFont'],
      'Cannot be referenced by name in @font-face src. Use system-ui or -apple-system CSS keywords.'),
  }),
  systemEntry({
    id: 'sf-mono',
    family: 'SF Mono',
    category: 'monospace',
    contexts: ['mono', 'data'],
    tags: ['code', 'system'],
    weights: [300, 400, 500, 600, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    metrics: {
      unitsPerEm: 2048, ascent: 1950, descent: -494, lineGap: 0,
      xHeight: 1060, capHeight: 1443, useTypoMetrics: true,
      hheaAscent: null, hheaDescent: null, winAscent: null, winDescent: null,
    },
    license: { type: 'Apple EULA', url: 'https://developer.apple.com/fonts/', commercial: true, selfHostable: false, attribution: 'Apple Inc.' },
    install: sys(['apple'], ['SFMono-Regular', 'SF Mono'], ['ui-monospace']),
  }),
  systemEntry({
    id: 'new-york',
    family: 'New York',
    category: 'serif',
    contexts: ['reading', 'editorial', 'display'],
    tags: ['transitional', 'system'],
    variable: true,
    axes: [{ tag: 'wght', name: 'Weight', min: 400, max: 900, default: 400, step: 1, cssProperty: 'font-weight' },
           { tag: 'opsz', name: 'Optical Size', min: 17, max: 144, default: 17, step: 0.1, cssProperty: 'font-optical-sizing' }],
    weights: [400, 500, 600, 700, 800, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    hasOpticalSizing: true,
    license: { type: 'Apple EULA', url: 'https://developer.apple.com/fonts/', commercial: true, selfHostable: false, attribution: 'Apple Inc.' },
    install: sys(['apple'], ['New York'], [], 'Available on macOS Catalina+ and iOS 13+.'),
  }),
  systemEntry({
    id: 'helvetica-neue',
    family: 'Helvetica Neue',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    tags: ['neo-grotesque', 'system'],
    weights: [100, 200, 300, 400, 500, 700, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    metrics: {
      unitsPerEm: 1000, ascent: 952, descent: -213, lineGap: 28,
      xHeight: 517, capHeight: 714, useTypoMetrics: false,
      hheaAscent: 952, hheaDescent: -213, winAscent: 975, winDescent: 217,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Linotype / Apple' },
    install: sys(['apple'], ['Helvetica Neue'], [],
      'Reliable local() target on Apple. Ships since OS X 10.7 / iOS 7.'),
  }),

  // ── Windows ──
  systemEntry({
    id: 'segoe-ui-variable',
    family: 'Segoe UI Variable',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    variable: true,
    axes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400, step: 1, cssProperty: 'font-weight' },
           { tag: 'opsz', name: 'Optical Size', min: 12, max: 120, default: 16, step: 0.1, cssProperty: 'font-optical-sizing' }],
    weights: [100, 200, 300, 350, 400, 600, 700, 800, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    hasOpticalSizing: true,
    tags: ['humanist', 'system'],
    metrics: {
      unitsPerEm: 2048, ascent: 2210, descent: -514, lineGap: 0,
      xHeight: 1024, capHeight: 1434, useTypoMetrics: true,
      hheaAscent: 2210, hheaDescent: -514, winAscent: 2210, winDescent: 514,
    },
    license: { type: 'Proprietary', url: 'https://learn.microsoft.com/en-us/typography/font-list/segoe-ui-variable', commercial: true, selfHostable: false, attribution: 'Microsoft' },
    install: sys(['windows'], ['Segoe UI Variable', 'Segoe UI'], [],
      'Pre-installed on Windows 11. Win10 has non-variable Segoe UI.'),
  }),
  systemEntry({
    id: 'cascadia-code',
    family: 'Cascadia Code',
    category: 'monospace',
    contexts: ['mono', 'data'],
    variable: true,
    axes: [{ tag: 'wght', name: 'Weight', min: 200, max: 700, default: 400, step: 1, cssProperty: 'font-weight' }],
    weights: [200, 300, 400, 600, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['code', 'ligatures', 'system'],
    license: { type: 'OFL-1.1', url: 'https://github.com/microsoft/cascadia-code/blob/main/LICENSE', commercial: true, selfHostable: true, attribution: 'Microsoft' },
    install: sys(['windows'], ['Cascadia Code', 'Cascadia Mono'], [],
      'Bundled with Windows Terminal. Also available as open-source download.'),
  }),
  systemEntry({
    id: 'consolas',
    family: 'Consolas',
    category: 'monospace',
    contexts: ['mono', 'data'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['code', 'system'],
    metrics: {
      unitsPerEm: 2048, ascent: 1884, descent: -514, lineGap: 0,
      xHeight: 1064, capHeight: 1462, useTypoMetrics: true,
      hheaAscent: 1884, hheaDescent: -514, winAscent: 2048, winDescent: 514,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Microsoft' },
    install: sys(['windows'], ['Consolas'], []),
  }),

  // ── Android / ChromeOS ──
  systemEntry({
    id: 'roboto-system',
    family: 'Roboto',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    variable: true,
    axes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400, step: 1, cssProperty: 'font-weight' }],
    weights: [100, 300, 400, 500, 700, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['neo-grotesque', 'system'],
    metrics: {
      unitsPerEm: 2048, ascent: 1900, descent: -500, lineGap: 0,
      xHeight: 1082, capHeight: 1456, useTypoMetrics: true,
      hheaAscent: 1900, hheaDescent: -500, winAscent: 1946, winDescent: 512,
    },
    license: { type: 'Apache-2.0', url: 'https://github.com/googlefonts/roboto/blob/main/LICENSE', commercial: true, selfHostable: true, attribution: 'Google' },
    install: sys(['android'], ['Roboto'], [],
      'Default system font on Android 4.0+. Also on Google Fonts.'),
  }),
  systemEntry({
    id: 'roboto-mono-system',
    family: 'Roboto Mono',
    category: 'monospace',
    contexts: ['mono', 'data'],
    weights: [100, 300, 400, 500, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['code', 'system'],
    license: { type: 'Apache-2.0', url: 'https://github.com/googlefonts/roboto-mono/blob/main/LICENSE', commercial: true, selfHostable: true, attribution: 'Google' },
    install: sys(['android'], ['Roboto Mono'], []),
  }),

  // ── Linux ──
  systemEntry({
    id: 'noto-sans-system',
    family: 'Noto Sans',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    variable: true,
    axes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400, step: 1, cssProperty: 'font-weight' }],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['humanist', 'system'],
    metrics: {
      unitsPerEm: 1000, ascent: 1069, descent: -293, lineGap: 0,
      xHeight: 536, capHeight: 714, useTypoMetrics: true,
      hheaAscent: 1069, hheaDescent: -293, winAscent: 1069, winDescent: 293,
    },
    license: { type: 'OFL-1.1', url: 'https://github.com/notofonts/notofonts.github.io/blob/main/LICENSE', commercial: true, selfHostable: true, attribution: 'Google' },
    install: sys(['linux'], ['Noto Sans'], [], 'Default sans on many Linux distributions.'),
  }),
  systemEntry({
    id: 'noto-serif-system',
    family: 'Noto Serif',
    category: 'serif',
    contexts: ['reading', 'editorial'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['transitional', 'system'],
    license: { type: 'OFL-1.1', url: 'https://github.com/notofonts/notofonts.github.io/blob/main/LICENSE', commercial: true, selfHostable: true, attribution: 'Google' },
    install: sys(['linux', 'android'], ['Noto Serif'], []),
  }),
  systemEntry({
    id: 'noto-sans-mono-system',
    family: 'Noto Sans Mono',
    category: 'monospace',
    contexts: ['mono', 'data'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    tags: ['code', 'system'],
    license: { type: 'OFL-1.1', url: 'https://github.com/notofonts/notofonts.github.io/blob/main/LICENSE', commercial: true, selfHostable: true, attribution: 'Google' },
    install: sys(['linux'], ['Noto Sans Mono'], []),
  }),
  systemEntry({
    id: 'dejavu-sans',
    family: 'DejaVu Sans',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['humanist', 'system'],
    license: { type: 'Bitstream Vera + Arev', url: 'https://dejavu-fonts.github.io/License.html', commercial: true, selfHostable: true, attribution: null },
    install: sys(['linux'], ['DejaVu Sans'], [], 'Traditional Linux fallback before Noto adoption.'),
  }),

  // ── Universal (available on all platforms) ──
  systemEntry({
    id: 'arial',
    family: 'Arial',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['neo-grotesque', 'universal'],
    metrics: {
      unitsPerEm: 2048, ascent: 1854, descent: -434, lineGap: 67,
      xHeight: 1062, capHeight: 1467, useTypoMetrics: false,
      hheaAscent: 1854, hheaDescent: -434, winAscent: 2007, winDescent: 435,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Monotype' },
    install: sys(['universal'], ['Arial'], [], 'Available on virtually every device.'),
  }),
  systemEntry({
    id: 'times-new-roman',
    family: 'Times New Roman',
    category: 'serif',
    contexts: ['reading'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['transitional', 'universal'],
    metrics: {
      unitsPerEm: 2048, ascent: 1825, descent: -443, lineGap: 87,
      xHeight: 916, capHeight: 1356, useTypoMetrics: false,
      hheaAscent: 1825, hheaDescent: -443, winAscent: 2000, winDescent: 454,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Monotype' },
    install: sys(['universal'], ['Times New Roman'], []),
  }),
  systemEntry({
    id: 'georgia',
    family: 'Georgia',
    category: 'serif',
    contexts: ['reading', 'editorial'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['transitional', 'universal'],
    metrics: {
      unitsPerEm: 2048, ascent: 1878, descent: -449, lineGap: 0,
      xHeight: 986, capHeight: 1419, useTypoMetrics: true,
      hheaAscent: 1878, hheaDescent: -449, winAscent: 1878, winDescent: 449,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Microsoft / Matthew Carter' },
    install: sys(['universal'], ['Georgia'], [], 'Screen-optimized serif. Available everywhere.'),
  }),
  systemEntry({
    id: 'courier-new',
    family: 'Courier New',
    category: 'monospace',
    contexts: ['mono'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['universal'],
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Monotype' },
    install: sys(['universal'], ['Courier New'], []),
  }),
  systemEntry({
    id: 'verdana',
    family: 'Verdana',
    category: 'sans-serif',
    contexts: ['interface', 'reading'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['humanist', 'universal'],
    metrics: {
      unitsPerEm: 2048, ascent: 2059, descent: -430, lineGap: 0,
      xHeight: 1117, capHeight: 1489, useTypoMetrics: true,
      hheaAscent: 2059, hheaDescent: -430, winAscent: 2059, winDescent: 430,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Microsoft / Matthew Carter' },
    install: sys(['universal'], ['Verdana'], [], 'Designed for screen readability. High x-height.'),
  }),
  systemEntry({
    id: 'tahoma',
    family: 'Tahoma',
    category: 'sans-serif',
    contexts: ['interface'],
    weights: [400, 700],
    tags: ['humanist', 'universal'],
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Microsoft / Matthew Carter' },
    install: sys(['universal'], ['Tahoma'], []),
  }),
  systemEntry({
    id: 'trebuchet-ms',
    family: 'Trebuchet MS',
    category: 'sans-serif',
    contexts: ['interface', 'display'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['humanist', 'universal'],
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Microsoft' },
    install: sys(['universal'], ['Trebuchet MS'], []),
  }),
  systemEntry({
    id: 'menlo',
    family: 'Menlo',
    category: 'monospace',
    contexts: ['mono', 'data'],
    weights: [400, 700],
    styles: ['normal', 'italic'],
    hasItalic: true,
    tags: ['code', 'system'],
    metrics: {
      unitsPerEm: 2048, ascent: 1901, descent: -483, lineGap: 0,
      xHeight: 1120, capHeight: 1493, useTypoMetrics: true,
      hheaAscent: 1901, hheaDescent: -483, winAscent: 1901, winDescent: 483,
    },
    license: { type: 'Proprietary', url: '', commercial: true, selfHostable: false, attribution: 'Apple' },
    install: sys(['apple'], ['Menlo'], [], 'Pre-installed on macOS. Based on DejaVu Sans Mono.'),
  }),
];
